# Generated by Django 6.0.3 on 2026-03-07 09:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('is_correct', models.BooleanField(default=False, help_text='AI 判断作业是否正确', verbose_name='是否正确')),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='AI 给出的分数（0-100）', max_digits=5, null=True, verbose_name='得分')),
                ('feedback', models.TextField(blank=True, help_text='AI 生成的详细评语和建议', verbose_name='AI 评语')),
                ('analysis', models.JSONField(blank=True, default=dict, help_text='AI 返回的详细分析结果（结构化数据）', verbose_name='详细分析')),
                ('graded_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='AI 完成批改的时间', verbose_name='批改时间')),
                ('model_version', models.CharField(blank=True, help_text='用于批改的大模型版本号', max_length=50, verbose_name='模型版本')),
                ('raw_response', models.JSONField(blank=True, default=dict, help_text='大模型返回的原始 JSON 响应数据', verbose_name='原始响应')),
            ],
            options={
                'verbose_name': 'AI 批改结果',
                'verbose_name_plural': 'AI 批改结果',
                'ordering': ['-graded_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('title', models.CharField(db_index=True, help_text='课程的标题，如 "Python 编程基础"', max_length=200, verbose_name='课程名称')),
                ('description', models.TextField(blank=True, help_text='课程的详细介绍和说明', verbose_name='课程描述')),
                ('max_students', models.PositiveIntegerField(default=50, help_text='课程允许的最大学生数量', verbose_name='最大学生数')),
                ('is_active', models.BooleanField(default=True, help_text='标记课程是否正在进行中', verbose_name='是否活跃')),
                ('teacher', models.ForeignKey(help_text='课程的创建者和授课教师', limit_choices_to={'groups__name': 'Teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='taught_courses', to=settings.AUTH_USER_MODEL, verbose_name='授课教师')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('title', models.CharField(db_index=True, help_text='作业的标题，如 "第一次 Python 练习"', max_length=200, verbose_name='作业标题')),
                ('description', models.TextField(help_text='作业的详细要求、任务描述和提交要求', verbose_name='作业说明')),
                ('requirements', models.TextField(blank=True, help_text='作业的具体技术要求、评分标准等', verbose_name='具体要求')),
                ('due_date', models.DateTimeField(db_index=True, help_text='作业提交的截止时间', verbose_name='截止时间')),
                ('max_score', models.PositiveIntegerField(default=100, help_text='作业的满分分数', verbose_name='满分分数')),
                ('allow_late_submission', models.BooleanField(default=False, help_text='是否允许学生在截止时间后提交', verbose_name='允许迟交')),
                ('is_published', models.BooleanField(default=True, help_text='标记作业是否已发布给学生可见', verbose_name='已发布')),
                ('course', models.ForeignKey(help_text='作业所属的课程', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '作业',
                'verbose_name_plural': '作业',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='学生加入课程的时间', verbose_name='加入时间')),
                ('course', models.ForeignKey(help_text='学生加入的课程', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='课程')),
                ('student', models.ForeignKey(help_text='选课的学生用户', limit_choices_to={'groups__name': 'Student'}, on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '课程选课记录',
                'verbose_name_plural': '课程选课记录',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='ErrorTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('tag_name', models.CharField(db_index=True, help_text='错误涉及的知识点名称，如 "循环语法"、"变量作用域"', max_length=100, verbose_name='知识点标签')),
                ('error_type', models.CharField(db_index=True, help_text='错误的具体类型，如 "语法错误"、"逻辑错误"、"性能问题"', max_length=100, verbose_name='错误类型')),
                ('description', models.TextField(blank=True, help_text='对该错误的具体描述和说明', verbose_name='错误描述')),
                ('severity', models.CharField(choices=[('low', '轻微'), ('medium', '中等'), ('high', '严重'), ('critical', '致命')], default='medium', help_text='错误的严重程度分级', max_length=20, verbose_name='严重程度')),
                ('suggestion', models.TextField(blank=True, help_text='AI 给出的针对该错误的改进建议', verbose_name='改进建议')),
                ('code_snippet', models.TextField(blank=True, help_text='出错的代码片段（用于定位问题）', verbose_name='错误代码片段')),
                ('line_number', models.PositiveIntegerField(blank=True, help_text='错误所在的代码行号（如果可定位）', null=True, verbose_name='行号')),
                ('ai_result', models.ForeignKey(help_text='关联的 AI 批改结果', on_delete=django.db.models.deletion.CASCADE, related_name='error_tags', to='courses.airesult', verbose_name='AI 批改结果')),
            ],
            options={
                'verbose_name': '错误知识点标签',
                'verbose_name_plural': '错误知识点标签',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('code_content', models.TextField(blank=True, help_text='学生提交的代码片段（纯文本格式）', verbose_name='代码内容')),
                ('image_urls', models.JSONField(blank=True, default=list, help_text='学生提交的截图或作业图片的 URL 列表', verbose_name='图片链接列表')),
                ('submission_text', models.TextField(blank=True, help_text='学生对作业的额外说明或注释', verbose_name='文字说明')),
                ('status', models.CharField(choices=[('pending', '待批改'), ('grading', '批改中'), ('completed', '已完成'), ('failed', '批改失败')], db_index=True, default='pending', help_text='作业批改的状态：待批改、批改中、已完成、批改失败', max_length=20, verbose_name='批改状态')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='学生提交作业的时间', verbose_name='提交时间')),
                ('is_late', models.BooleanField(default=False, help_text='标记是否在截止时间后提交', verbose_name='是否迟交')),
                ('assignment', models.ForeignKey(help_text='提交的作业', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.assignment', verbose_name='作业')),
                ('student', models.ForeignKey(help_text='提交作业的学生', limit_choices_to={'groups__name': 'Student'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL, verbose_name='提交学生')),
            ],
            options={
                'verbose_name': '作业提交',
                'verbose_name_plural': '作业提交',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='airesult',
            name='submission',
            field=models.OneToOneField(help_text='关联的作业提交记录', on_delete=django.db.models.deletion.CASCADE, related_name='ai_result', to='courses.submission', verbose_name='作业提交'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['teacher', 'is_active'], name='courses_cou_teacher_184db5_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['course', 'is_published'], name='courses_ass_course__e11abf_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['due_date'], name='courses_ass_due_dat_e405cf_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['student', 'joined_at'], name='courses_cou_student_addc68_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['course', 'joined_at'], name='courses_cou_course__58c80b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together={('student', 'course')},
        ),
        migrations.AddIndex(
            model_name='errortag',
            index=models.Index(fields=['tag_name'], name='courses_err_tag_nam_1eff98_idx'),
        ),
        migrations.AddIndex(
            model_name='errortag',
            index=models.Index(fields=['error_type'], name='courses_err_error_t_af3ce6_idx'),
        ),
        migrations.AddIndex(
            model_name='errortag',
            index=models.Index(fields=['severity'], name='courses_err_severit_ea08c5_idx'),
        ),
        migrations.AddIndex(
            model_name='errortag',
            index=models.Index(fields=['ai_result', 'tag_name'], name='courses_err_ai_resu_4b478e_idx'),
        ),
        migrations.AddIndex(
            model_name='errortag',
            index=models.Index(fields=['tag_name', 'error_type'], name='courses_err_tag_nam_894587_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student', 'status'], name='courses_sub_student_f20316_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['assignment', 'status'], name='courses_sub_assignm_64be56_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', 'submitted_at'], name='courses_sub_status_6f6df0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('assignment', 'student')},
        ),
        migrations.AddIndex(
            model_name='airesult',
            index=models.Index(fields=['is_correct'], name='courses_air_is_corr_ea32dd_idx'),
        ),
        migrations.AddIndex(
            model_name='airesult',
            index=models.Index(fields=['graded_at'], name='courses_air_graded__2ed59e_idx'),
        ),
    ]
