# Generated by Django 6.0.3 on 2026-03-07 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', '学生'), ('teacher', '教师')], default='student', help_text='用户角色：学生或教师', max_length=20, verbose_name='角色')),
                ('real_name', models.CharField(blank=True, help_text='用户的真实姓名', max_length=100, verbose_name='真实姓名')),
                ('avatar', models.URLField(blank=True, help_text='用户头像的图片链接', verbose_name='头像 URL')),
                ('phone', models.CharField(blank=True, help_text='用户的手机号码', max_length=20, verbose_name='手机号')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(help_text='关联的 Django 原生用户', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
                'db_table': 'courses_userprofile',
                'indexes': [models.Index(fields=['role'], name='courses_use_role_bc9fb4_idx'), models.Index(fields=['user', 'role'], name='courses_use_user_id_c7b07f_idx')],
            },
        ),
    ]
